version: "3.9"
services:
  postgres:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=wallet
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  zookeeper:
      image: "bitnami/zookeeper:3.8-debian-10"
      ports:
          - "2181:2181"
      environment:
          - ALLOW_ANONYMOUS_LOGIN=yes
      restart: always

  kafka:
      image: "bitnami/kafka:3.1-debian-10"
      ports:
          - "29092:29092"
      environment:
          - KAFKA_BROKER_ID=1
          - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092
          - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:29092
          - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
          - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
          - zookeeper
      restart: always


  # redis:
  #   image: redis:7-alpine
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #     - "9090:9090"
  #   environment:
  #     - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
  #     - REDIS_ADDRESS=redis:6379
  #   depends_on:
  #     - postgres
  #     - redis
  #   entrypoint:
  #     [
  #       "/app/wait-for.sh",
  #       "postgres:5432",
  #       "--",
  #       "/app/start.sh"
  #     ]
  #   command: [ "/app/main" ]
volumes:
  data-volume:
